name: Samsung GKI Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
    - name: Free up workflow space
      run: |
        curl -L -o util_free_space.sh https://raw.githubusercontent.com/apache/arrow/main/ci/scripts/util_free_space.sh
        chmod +x util_free_space.sh
        ./util_free_space.sh

    - name: Import Kernel Source
      uses: actions/checkout@v4

    - name: Install Required Package
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential bc bison flex libssl-dev make libncurses5-dev git curl clang lld \
        libelf-dev erofs-utils android-sdk-libsparse-utils build-essential automake autoconf libtool pkg-config fuse3 e2fsprogs pv liblz4-dev uuid-dev \
        libfuse3-dev fuse3 f2fs-tools fuse2fs attr zlib1g-dev rsync \
        device-tree-compiler lz4 xz-utils zlib1g-dev openjdk-17-jdk gcc g++ python3 python-is-python3 p7zip-full \
        pv uuid-dev libfuse3-dev f2fs-tools fuse2fs attr ccache

    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2.19
      with:
        key: ccache
        max-size: 5G
        append-timestamp: false
        create-symlink: true
        job-summary: 'CCache stats'
        evict-old-files: 'job'

    - name: Add ccache to PATH
      run: |
        echo "/usr/lib/ccache" >> $GITHUB_PATH

    - name: Setting Scripts Permission
      run: |
        chmod +x build.sh

    - name: Kernel Build
      run: |
        ./build.sh

    - name: Cleanup old ccache
      shell: bash
      run: |
        set -euo pipefail
        echo "Deleting old ccache..."
        gh cache delete ccache- || true

    - name: Final Build Summary
      shell: bash
      run: |
        set -euo pipefail
        {
          echo "### Build Summary"
          echo ""
          echo "CCache Statistics :"
          echo "$(ccache -s -v)"
        } >> "$GITHUB_STEP_SUMMARY"

    - name: Upload KernelSU Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "Fold5_KernelSU_File"
        path: |
          ./*.img
          ./*.tar
        if-no-files-found: ignore 

    - name: Upload Kernel Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "Fold5_Kernel_File"
        path: |
          ./out/msm-kalama-kalama-gki/dist/Image
          ./out/msm-kalama-kalama-gki/dist/Image-gz
          ./out/msm-kalama-kalama-gki/dist/*.dtb
          ./out/msm-kalama-kalama-gki/dist/*.dtbo
          ./out/msm-kalama-kalama-gki/dist/dtbo.img
          ./out/msm-kalama-kalama-gki/dist/*.ko
        if-no-files-found: ignore

    - name: Upload Dist Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "Fold5_Kernel_dist_File"
        path: |
          ./out/msm-kalama-kalama-gki/dist/*
        if-no-files-found: ignore
        retention-days: 3