name: Samsung GKI Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      LDCACHE_DIR: ${{ github.workspace }}/.lto_cache
      CCACHE_COMPILERCHECK: "content"
      CCACHE_NOCOMPRESS: "true"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      CCACHE_MAXSIZE: "0"
      CCACHE_NODEPEND: "true"
      CCACHE_IGNOREOPTIONS: "--sysroot*"
      CCACHE_DIRECT: "true"
      CCACHE_FILECLONE: "true"
      CCACHE_INODE_CACHE: "true"
      CCACHE_UMASK: "002"
      CCACHE_SLOPPINESS: "file_macro,time_macros,include_file_mtime,include_file_ctime,pch_defines,system_headers,locale,modules"
      CCACHE_IS_KERNEL_COMPILING: "true"

    steps:
    - name: Free up workflow space
      run: |
        curl -L -o util_free_space.sh https://raw.githubusercontent.com/apache/arrow/main/ci/scripts/util_free_space.sh
        chmod +x util_free_space.sh
        ./util_free_space.sh

    - name: Import Kernel Source
      uses: actions/checkout@v4

    - name: Install Required Package
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential bc bison flex libssl-dev make libncurses5-dev git curl clang lld \
        libelf-dev erofs-utils android-sdk-libsparse-utils build-essential automake autoconf libtool pkg-config fuse3 e2fsprogs pv liblz4-dev uuid-dev \
        libfuse3-dev fuse3 f2fs-tools fuse2fs attr zlib1g-dev rsync \
        device-tree-compiler lz4 xz-utils zlib1g-dev openjdk-17-jdk gcc g++ python3 python-is-python3 p7zip-full \
        pv uuid-dev libfuse3-dev f2fs-tools fuse2fs attr

    - name: Install ccache with ECS by cctv18
      shell: bash
      run: |
        set -euo pipefail
        echo "::group::Install ccache with ECS"
        wget -q https://github.com/nullptr-t-oss/kernel_patches/raw/refs/heads/main/bin/ccache-x86-64 -O ccache
        sudo cp -f ./ccache /usr/bin/ccache
        sudo chmod +x /usr/bin/ccache
        rm -f ./ccache

        echo "[DEBUG] Ccache version : $(ccache --version)"
        echo "::endgroup::"

    - name: Configure ccache & LTO caching
      shell: bash
      run: |
        set -euo pipefail

        mkdir -p "$CCACHE_DIR"
        mkdir -p "$LDCACHE_DIR"

        ccache -o compression=false
        ccache -M 5G

        echo '#!/bin/bash' > ld-wrapper
        echo 'ld.lld "$@" --thinlto-cache-dir=$LDCACHE_DIR --thinlto-jobs=$(nproc --all)' >> ld-wrapper
        chmod +x ld-wrapper

    - name: Restore ccache
      uses: actions/cache/restore@v5
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ccache
        restore-keys: ccache

    - name: Restore LTO cache
      uses: actions/cache/restore@v5
      with:
        path: ${{ env.LDCACHE_DIR }}
        key: LTO
        restore-keys: LTO

    - name: Setting Scripts Permission
      run: |
        chmod +x build.sh

    - name: Kernel Build
      run: |
        ./build.sh

    - name: Cleanup old ccache & LTO cache
      shell: bash
      run: |
        set -euo pipefail
        echo "Deleting old ccache..."
        gh cache delete ccache || true
        gh cache delete LTO || true

    - name: Save ccache
      uses: actions/cache/save@v5
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ccache

    - name: Save LTO cache
      uses: actions/cache/save@v5
      with:
        path: ${{ env.LDCACHE_DIR }}
        key: LTO

    - name: Final Build Summary
      shell: bash
      run: |
        set -euo pipefail
        {
          echo "### Build Summary"
          echo ""
          echo "> [!IMPORTANT]"
          echo "> CCache Statistics :"
          echo "> $(ccache -s -v)"
        } >> "$GITHUB_STEP_SUMMARY"

    - name: Upload KernelSU Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "Fold5_KernelSU_File"
        path: |
          ./*.img
          ./*.tar
        if-no-files-found: ignore 

    - name: Upload Kernel Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "Fold5_Kernel_File"
        path: |
          ./out/msm-kalama-kalama-gki/dist/Image
          ./out/msm-kalama-kalama-gki/dist/Image-gz
          ./out/msm-kalama-kalama-gki/dist/*.dtb
          ./out/msm-kalama-kalama-gki/dist/*.dtbo
          ./out/msm-kalama-kalama-gki/dist/dtbo.img
          ./out/msm-kalama-kalama-gki/dist/*.ko
        if-no-files-found: ignore

    - name: Upload Dist Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "Fold5_Kernel_dist_File"
        path: |
          ./out/msm-kalama-kalama-gki/dist/*
        if-no-files-found: ignore
        retention-days: 3